### ISSUE TITLE
'Value too great for base' error from one-queue.sh lines 183, 194, 969

### ISSUE THREAD

**Issue by ahueb** [VirtualFlow/VFVS#13]
I began noticing some errors which were causing joblines to fail occasionally. It seems that the error stems from the millisecond calculation located in three places within the 'one-queue.sh' script:

$(date +'%s * 1000 + %-N / 1000000')

I was getting an error concerning the value produced by '%-N' which would occasionally begin with a '0' (zero). It seems this was being interpreted as an octal value rather than decimal, and by prepending '10#' to the '%-N' command, the value is forced to be considered as a decimal no matter what the first character is:

$(date +'%s * 1000 + 10#%-N / 1000000')

It appears that this has prevented the error from recurring, although I am still testing.

Has anyone else experienced this error?

**Comment by cgorgulla** [comment]
Thank you for the hint. The problems seems to come from the new bash versions >= bash 4.4. I've fixed this, should work now also with the new versions of bash.
