### ISSUE TITLE
Using VFVS without batch management system

### ISSUE THREAD

**Issue by Phytoecia** [VirtualFlow/VFVS#17]
Hello,

I am trying to use VFVS for docking in our Unix system.
As our server does not run any batch management system, I cannot fill in the all.ctrl file and this cause errors.
Is there any way to directly run VFVS without batch management?

**Comment by cgorgulla** [comment]
There might be two ways on how you could potentially make it work:

1. One could install slurm on your server as single node cluster. See for instance here: https://drtailor.medium.com/how-to-setup-slurm-on-ubuntu-20-04-for-single-node-work-scheduling-6cc909574365
I have not tried that yet by myself. 

2. Changing the VirtualFlow Code such that it does not require slurm or any other batch system. This should not be too difficult, but requires some programming experience.

**Comment by Phytoecia** [comment]
Hello,

I tried the first solution and it works perfectly.
Thanks a lot for your kind help :)
I'll close this issue.
