### ISSUE TITLE
How to use docking programs not in the choice list? (Autodock-GPU)

### ISSUE THREAD

**Issue by To-phoenix-zhw** [VirtualFlow/VFVS#19]
As mentioned in the original article, “VirtualFlow is able to use a variety of the most powerful docking programs.”Is it possible to connect to the VF platform via Autodock-GPU (https://github.com/ccsb-scripps/AutoDock-GPU) ? If so, by what steps? Thanks!

**Comment by cgorgulla** [comment]
We have just added AutoDock GPU to VirtualFlow. We will update the code in the GitHub repo in a few days, stay tuned :-)

**Comment by JoshuaMeyers** [comment]
Hi Guys, nice tool! I am also interested in adding a docking program (but not AutoDock-GPU). In my case it would be a commercial system such as GOLD, Glide or OEDocking - I am happy to implement myself but would it be possible to add some notes on how this could be achieved (or if its possible)?

Many thanks in advance

**Comment by akshat998** [comment]
Hi @JoshuaMeyers,

We are sorry for the late response. Could you please review the VFVS-2 branch of our repository? We have recently integrated GOLD and Glide into this branch (just docking; scoring functions still need to be merged in). It's important to note that both methods necessitate licenses, which users need to acquire and install independently :)

Best regards,
Akshat
