### ISSUE TITLE
Can the python-develop branch be used well now?

### ISSUE THREAD

**Issue by freeenergylab** [VirtualFlow/VFVS#20]
I wonder if the python-develop branch can be used to do large scale virtual screening now? And, what format for ligand-library?

**Comment by cgorgulla** [comment]
Yes, it can be used. The same format for the ligand library than for the bash version can be used (meta-tranche), and in addition a new format (hash) that will be described soon via the documentation and tutorials.

**Comment by freeenergylab** [comment]
Done, closed now.
