### ISSUE TITLE
Incomplete command in VFVS tutorial 1

### ISSUE THREAD

**Issue by bdelabarre** [VirtualFlow/VFVS#3]
On this page for the VFVS Tutorial-1:

https://docs.virtual-flow.org/tutorials/-LdE94b2AVfBFT72zK-v/vfvs-tutorial-1/the-completed-workflow#complete-ligand-ranking

There is a command given as:

vfvs_pp_ranking_all.sh ../../output-files/complete/ 2 meta

Reading through the ranking_all.sh script looks like it should be either .... "/ 2 meta_tranch" or "/ 2 meta_collection"

I used the meta_tranch argument which seemed to work.

Typing as described in the tutorial ( "/ 2 meta") results in a crash that is hard to diagnose (well maybe not that hard since I think I managed it here...)

**Comment by cgorgulla** [comment]
@bdelabarre Thank you very much for the hint, we have fixed it. In the latest version the argument is "meta_tranche".
