### ISSUE TITLE
Collection-length file download button currently broken

### ISSUE THREAD

**Issue by EricBoittier** [VirtualFlow/VFVS#4]
Hi Christoph, I just wanted to point out a bug on your website, currently the download button for the collection-length file is broken.

Inspecting the elements of your webpage I see:

`VM144:1 Uncaught SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at jsonToStrMap (generator.js:667)
    at HTMLButtonElement.<anonymous> (generator.js:606)
    at HTMLButtonElement.dispatch (jquery.js:2)
    at HTMLButtonElement.y.handle (jquery.js:2)`

I am able to generate my own collection-length file using bash commands but hopefully you can resolve this issue.

Hope that helps, Eric

**Comment by malets12** [comment]
Hi Eric,

Thanks for response!
I'm going to block that download button in new version, until required JSONs are not loaded.

For now, please, wait until you see 2 messages in browser's console:
```
Worker: JSON from URL collections_tmp.json loaded
Worker: JSON from URL collections.json loaded
```
and then download button should work correctly.

Yehor

**Comment by cgorgulla** [comment]
Hi @EricBoittier 

Thank you for the hint, we appreciate it. 

@malets12 Thanks for improving the web interface, the new version is nice :-)
