### ISSUE TITLE
Job Configuration/Memory Error

### ISSUE THREAD

**Issue by JSanchez61** [VirtualFlow/VFVS#42]
Hello,

I am trying to use VirtualFlow on the Texas Advanced Computing Center (TACC) but I have run into a job configuration error and a subsequent memory error. I am unsure if the two are related, so I will discuss them both here.

TACC is configured such that you cannot submit a job from a compute node (only a login node), so I am trying to avoid using that functionality. Moreover, on TACC the preferred approach is to submit one job with many nodes, instead of many jobs with one/few nodes. I believe VirtualFlow can still be configured to meet these needs, so I will outline my general approach here.

Attached are relevant screenshots of the .ctrl and .slurm files.

These produced the following error when I submitted them using ./vf_start_jobline.sh:

sbatch: error: Batch job submission failed: Requested node configuration is not available
However, I was able to circumvent this error when I commented out the --cpus-per-task #SBATCH directive. Notably, when I simply delete the directive instead of commenting it out, I also obtain an error and the job does not enter the queue. Why is that?

Also, when I analyze the workflow via ./vf_report.sh (on the job with the --cpus-per-task directive commented out) I notice that none of the ligands were processed (see attached report screenshot).

Of course, I looked at the job file (also attached) to see if I could glean what the issue was. It seems to be related to memory/storage. I cannot think of how to remedy this, though.

Also, from the job file, I noticed that there 10 job steps, but they are all appearing to execute on the same node (c451-042).

i.e.:

Starting job step 1 on host c451-042.stampede2.tacc.utexas.edu
Starting job step 2 on host c451-042.stampede2.tacc.utexas.edu
…
Starting job step 10 on host c451-042.stampede2.tacc.utexas.edu

My intention is to spread out computational and memory loads against the nodes that request. I am not sure if I did something wrong in the .ctrl or the .slurm files, though.

I would really appreciate help if anyone has a solution. I think VirtualFlow is a fantastic tool and I look forward to using it on my research!
<img width="1681" alt="all_attachments" src="https://user-images.githubusercontent.com/56413817/228974989-835eaa43-407d-4807-a2c9-fbe63a0f7e38.png">

**Comment by akshat998** [comment]
Hi @JSanchez61 ,

Thank you for detailing your experience with running VirtualFlow at TACC (& sorry for the late response). It seems you're facing a couple of challenges, namely the job configuration error and a potential memory issue, which we can address.

Firstly, the sbatch error related to the node configuration suggests that your request might not match the available resources at TACC. It's interesting that commenting out the --cpus-per-task directive circumvents this issue. This could be a clue that the default configuration of TACC might not align with what you initially specified. When you remove the directive completely, sbatch might revert to default settings that are incompatible with your job, hence the error.

For the issue of none of the ligands being processed, this could indeed be a memory or resource allocation issue. If VirtualFlow isn't provided with sufficient resources, it may not be able to process the workload as expected.

Regarding the job steps all executing on the same node, this could be an indication that your .slurm file may not be set up to distribute the load across multiple nodes. Typically, you would need to specify node distribution in your .slurm file to ensure that the computational load is spread out as intended. I would perhaps suggest looking at the default submission file at TACC (they should have one at the homepage), and modifying the submit.sh file accordingly? (just trying to run a single calculation successfully would tell a ton!) :)  

Regards
Akshat

**Comment by akshat998** [comment]
Please feel free to re-open this issue, as needed :)
