### ISSUE TITLE
Can VFVS can be used in the hydrated docking?

### ISSUE THREAD

**Issue by TobiasWinter97** [VirtualFlow/VFVS#46]
The crystallization structure of my protein includes 4 water molecules to interact with the ligand, could you please tell me if I should use the hydrated docking method in VFVS? If so, how could I do it? Thanks!

**Comment by akshat998** [comment]
Hi @TANGLi83-star,

We apologize for the delay in responding to your query.

You can find a comprehensive list of the docking software we support in our recent paper, available at: https://www.biorxiv.org/content/10.1101/2023.04.25.537981v1.abstract.

As for your question about hydrated docking, I am not certain offhand which of our supported methods accommodate this feature. However, should any of them offer hydrated docking as an option, it would simply require modifications to the input file to utilize this functionality.

Best of luck with your work! :)

Best regards,
Akshat
