### ISSUE TITLE
Invalid directive found in batch script:

### ISSUE THREAD

**Issue by Nagasundaram620** [VirtualFlow/VFVS#47]
I have followed the VFVS tutorial precisely and prepared all the files and folders as per the tutorial. But I am facing the error
sbatch: error: Invalid directive found in batch script: be
Error was trapped which is a nonstandard error.
Error was trapped which is a nonstandard error.
Error in bash script submit.sh
Error in bash script submit.sh
Error on line 68
Error on line 68

I can't understand the problem exactly.  Need help to solve this error

**Comment by akshat998** [comment]
Hi @Nagasundaram620,

Apologies for the delayed reply. To assist you better, could you please provide the submission script (submit.sh) you're currently using? It's quite possible that the format of the submission script varies for your specific cluster environment. I recommend reviewing a template example from your cluster's homepage and adjusting your script to align with the format and requirements specific to your cluster :) 

Best regards,
Akshat

**Comment by akshat998** [comment]
Please feel free to re-open this issue, as needed :)
