### ISSUE TITLE
REAL Space files can not be downloaded

### ISSUE THREAD

**Issue by ylyzz21** [VirtualFlow/VFVS#50]
Hi Gorgulla,

I am trying to use a subset of REAL Space for docking using [this link](https://real-tranches-wget-clean.netlify.app/). However,
there is no response when clicking **wget**. The content downloaded by **URLs** and **PowerShell** seems to be the local location rather than an address that I can download. For example,

**URLs:**
127.0.0.1/AF/AFAABABBCCAABAAAAA.tar
127.0.0.1/AF/AFAABABBCCAABABAAB.tar

**PowerShell:**
Invoke-WebRequest 127.0.0.1/AF/AFAABABBCCAABAAAAA.tar -OutFile AF/AFAABABBCCAABAAAAA.tar
Invoke-WebRequest 127.0.0.1/AF/AFAABABBCCAABABAAB.tar -OutFile AF/AFAABABBCCAABABAAB.tar

I don't know how to use these information to download the REAL Space subset I want.

Could you please help me to resolve this issue or suggest any further steps I can take to troubleshoot it? I appreciate any help you can provide.

Thank you,
Kaiyue

**Comment by akshat998** [comment]
Hi @ylyzz21, 

I believe that this is not the latest link for the REAL Space. Could you please give the following a try? 
https://virtual-flow-8c3b9.web.app/

Regards
Akshat

**Comment by ylyzz21** [comment]
Hi Akshat,

Thank you for your enthusiastic reply, I am very happy to see the latest link. I see that the 'get script' button seems to require a 'complete todofile'. Could you kindly tell me where this file is If it's convenient for you?

Thanks,
Kaiyue

**Comment by csecker** [comment]
Hi @ylyzz21,

the complete todo file can be obtained from the aws bucket, where also the library is stored (https://registry.opendata.aws/vf-libraries/). You need to request access via the form on the bottom of this page: https://virtual-flow.org/real-space-2022q12

After you have been granted access, you can get the todo file from the s3 bucket (s3://vf-libraries/) using e.g. the aws command line tool.

The script generated by the selector tool on https://virtual-flow.org/real-space-2022q12-interactive-tranche-table can then be used to generate a smaller subset todo file from the complete to do file (comprising only the tranches that were selected by you).

Please let us know if you have further questions!

Best
Chris
