### ISSUE TITLE
virtualflow and scratch

### ISSUE THREAD

**Issue by TommyBiomodellingAU** [VirtualFlow/VFVS#51]
does Virtualflow automatically perform the docking calculations in the scratch folder when using slurm as batchsystem?

Thanks,
Tommy

**Comment by akshat998** [comment]
Hi @TommyBiomodellingAU,

Apologies for the delayed response. VirtualFlow (VF) executes calculations in a temporary folder, where all the temporary docking files are generated. Upon completion, a zipped version of the directories, containing all the docked poses, is transferred back to the location where VF is cloned.

We recommend using the scratch folder for cloning the VF repository, as it typically accommodates the largest number of files and has the most storage capacity.

Hope this helps! :) 

Regards,
Akshat
