### ISSUE TITLE
convert output pdbqt files to smiles EFFICIENTLY

### ISSUE THREAD

**Issue by TheJankCoder** [VirtualFlow/VFVS#53]
Hi VirtualFlow developers

I find very confusing and cumbersome to convert the results files (which are in pdbqt files) to file containing compoundID and SMILES only. it is not very clear how to do this using VFTools, as the script vfvs_prepare_compoundids2smiles.sh already requires the ligand library to be in smiles format. 
How would one do this? it is super frustrating to not have an optimal of doing that. Maybe VFVS should automatically output a compoundID,SMILES,docking_score file such that post-docking cheminformatical analysis become easier

Please help me on this.

**Comment by akshat998** [comment]
Hello, 

Thank you for the question. @csecker I was wondering if you could look into this? 

Regards
Akshat

**Comment by TommyBiomodellingAU** [comment]
This is also a huge issue for me.

Making my own python script to trawl through the output-files/results/docking-scenario/meta_tranche folder fails on so many issues with the compressed files (EOFError, BadGzipFile etc) making it hard to make a functional script when you 100+ million docking results

**Comment by csecker** [comment]
Hi @TheJankCoder and @TommyBiomodellingAU,

thanks for using VirtualFlow and coming up with this issue. Are you using the bash (vfvs-1 branch) or python (vfvs-2 branch) version of VFVS? The python version automatically generates a summary or summary files that contain this information. For the bash version I have to check the VFTools scripts, but there should be one to get such a summary, too!

Best regards
Chris

**Comment by TheJankCoder** [comment]
Thanks for the response.
I am using the bash version (vfvs-1 branch) because it would submit readily to my local HPC cluster, which the python version would not. 
I am currently screening 125 million molecules (600GB of output data), which is a fairly large amount of data to handle. 
Also how would you recommend performing post-docking pose-clustering of diverse molecules in the virtualflow file structure? e.g clustering different ligands, that have similar poses, and pick diverse representatives that way?

**Comment by csecker** [comment]
Hi @TheJankCoder,

when using the VFVS bash version you should be able to extract a total ranking of your docking results (including compound ids and SMILES) using the `vfvs_pp_ranking_all.sh` script (https://github.com/VirtualFlow/VFTools/blob/vftools-1/bin/vfvs_pp_ranking_all.sh). This is also mentioned in one of the VF Tutorials: https://docs.virtual-flow.org/tutorials-vf1/vfvs-tutorial-1-bash/the-completed-workflow

Please let us know if you experience any issue with extracting the ranking/summary with this approach.

Best regards
Chris

**Comment by TommyBiomodellingAU** [comment]
the issue for me seems perhaps to be that the workflow is not fully completed (like 99% done, 200 collections left out of 110K collections), but a lot of docked molecules are still trapped in the incomplete folder. 

When i run the `vfvs_pp_ranking_all.sh` script i do get a firstposes.all.minindex.sorted.clean file, but it does not contain any smiles. Subsequently running the `vfvs_pp_prepare_dockingposes.sh` script fails immediately because some of the top ranked molecules are stil in the incomplete folder.

**Comment by TommyBiomodellingAU** [comment]
vfvs_pp_prepare_dockingposes.sh ../../../output-files/complete/qvina02_rigid_receptor1/results/ meta_tranche compounds dockingsposes overwrite


*********************************************************************
                  Extracting the winning structrures                 
*********************************************************************

 * The output folder dockingsposes does already exist. Removing...

 *** Preparing structure Z1001166432_1_T1 ***
ls: cannot access *replica*pdbqt: No such file or directory
rm: cannot remove ‘GEBBCE*’: No such file or directory
Error was trapped
Error in bash script vfvs_pp_prepare_dockingposes.sh
Error on line 159

**Comment by csecker** [comment]
OK, thanks for the feedback. I will need to test this to make sure there is no problem in the scripts. Just to double check the folder format you are using - can you post the folder structure of your output-files folder?

**Comment by csecker** [comment]
Do your collection summary files in output-files/complete/docking_scenario/summaries/metatranche/tranche folder contain a SMILES column? Just to make sure you have been using the version that supports this. This was added ~2 years ago: https://github.com/VirtualFlow/VFVS/commit/6f72ef9a9d8a095a546d34a0718b3dba9815d0f3

**Comment by TommyBiomodellingAU** [comment]
nope it does not. I just downloaded vfvs from the master branch from the github. I assumed it would be the most updated version of the vfvs-script

**Comment by TommyBiomodellingAU** [comment]
is it possible to update the summary files with the new version of `one-queue.sh` script without having to re-do 125 million dockings? it seems to be the  `one-queue.sh` script that is responsible for fetching the SMILES for each molecule?

**Comment by csecker** [comment]
There will be a solution without re-doing the dockings, but let's see what might be the best here. 

What docking program did you use? Could you check if your output docking files (e.g. pdbqt in output-files/complete/docking_scenario/results/metatranche/tranche/collection contain the smiles somewhere)? E.g. as a REMARK. If you used one of the ready-to-dock libraries, the input pdbqt files should also contain the SMILES string. Then one can extract them relatively easy similar to the line in the updated `one-queue.sh`.

If you used a custom library and neither your input ligand files nor your output docking files contain the SMILES string, I can provide a script that automatically converts the docking output files to SMILES. It currently supports converting the Autodock Vina output format (pdbqt) to SMILES but could be modified to work with other output formats, too. It might be a bit slow though.

**Comment by TommyBiomodellingAU** [comment]
I used tranches from the ENAMINE REAL space available from your homepage using quickvina02 for the dockings. They do contain smiles in the output-files. 
The speed is the most annoying thing when working with 100+ million molecules, but i guess there are no quick solutions for that

**Comment by csecker** [comment]
OK, perfect - then the files contain the SMILES string as a REMARK. You can e.g. go through the lines of your `firstposes.all.minindex.sorted.clean` file and extract each ligand's SMILES from the qvina02 results files with the following bash command:

`smiles=$(tar -xzOf complete/docking_scenario/results/metatranche/tranche/collection.tar.gz collection/ligand_replica-1.pdbqt | sed '/ENDMDL/q' | grep SMILES | awk '{print $NF}')`

with the metatranche, tranche, collection and ligand names from each line of the `firstposes.all.minindex.sorted.clean` file, e.g. 

`smiles=$(tar -xzOf complete/docking_scenario/results/AA/AAAAAA/00000.tar.gz 00000/ligand_replica-1.pdbqt | sed '/ENDMDL/q' | grep SMILES | awk '{print $NF}')`

In your bash script, you can then print it together with the other elements of the firstposes file to generate a ranking/summary file with SMILES. If it takes too long, you can also parallelize this. Let me know if you need support with such a script

**Comment by csecker** [comment]
Regarding extraction of docking poses, you should be able to use the following command (from e.g. a `VFVS/pp/ranking/docking_scenario` folder that contains the `firstposes.all.minindex.sorted.clean` file):

`vfvs_pp_prepare_dockingposes.sh ../../../output-files/complete/docking_scenario/results meta_collection firstposes.all.minindex.sorted.clean docking_poses_output_folder overwrite`

I just fixed a small bug in the `vfvs_pp_prepare_dockingposes.sh` script, so please make sure to use the one from the latest pull request (_should be merged in a few hours_). It should also get the poses from incomplete collections. Please also make sure to use the correct `folder_format` (e.g. `meta_collection`, `meta_tranche`, ...)

**Comment by TommyBiomodellingAU** [comment]
Also, the `firstposes.all.minindex.sorted.clean` is not sorted according to docking score, though it should be, right?

**Comment by csecker** [comment]
Yes, it should! To troubleshoot this, you can post the output of the `vfvs_pp_ranking_all.sh` script. At some point it calls `vfvs_pp_firstposes_prepare_ranking.sh`, which performs the ranking/sorting. Please also make sure to use the version from the latest commit of VFTools

**Comment by TommyBiomodellingAU** [comment]
> OK, perfect - then the files contain the SMILES string as a REMARK. You can e.g. go through the lines of your `firstposes.all.minindex.sorted.clean` file and extract each ligand's SMILES from the qvina02 results files with the following bash command:
> 
> `smiles=$(tar -xzOf complete/docking_scenario/results/metatranche/tranche/collection.tar.gz collection/ligand_replica-1.pdbqt | sed '/ENDMDL/q' | grep SMILES | awk '{print $NF}')`
> 
> with the metatranche, tranche, collection and ligand names from each line of the `firstposes.all.minindex.sorted.clean` file, e.g.
> 
> `smiles=$(tar -xzOf complete/docking_scenario/results/AA/AAAAAA/00000.tar.gz 00000/ligand_replica-1.pdbqt | sed '/ENDMDL/q' | grep SMILES | awk '{print $NF}')`
> 
> In your bash script, you can then print it together with the other elements of the firstposes file to generate a ranking/summary file with SMILES. If it takes too long, you can also parallelize this. Let me know if you need support with such a script

So, the filetypes in my metatranche/tranche/collection hierachy is in my case folder/tranche.tar/collection.tar.gz

**Comment by csecker** [comment]
Then you should be able to do something like:

`smiles=$(tar -xOf complete/docking_scenario/results/tranche.tar tranche/collection.tar.gz | tar -xzOf - collection/ligand_replica-1.pdbqt | sed '/ENDMDL/q' | grep SMILES | awk '{print $NF}')`

**Comment by akshat998** [comment]
Please feel free to re-open the issue if it is not resolved :) 

Regards
Akshat
