### ISSUE TITLE
Running VFVS on AWS Batch.

### ISSUE THREAD

**Issue by dxu104** [VirtualFlow/VFVS#58]
I am working to assist more customers with running VFVS on AWS Batch.

I have a concern regarding the configuration of VFVS 2.0. We specified the receptor file path in the config.txt as shown below:

receptor = ../input-files/receptors/qvina02_rigid_receptor1/receptor1.pdbqt

Despite our debugging efforts, we keep encountering the following error:
**Error: could not open "../input-files/receptors/qvina02_rigid_receptor1/receptor1.pdbqt" for reading.**

Is there a way to specify the receptor path via the command line instead of through config.txt? Also, do you know of anyone who has successfully set up VFVS 2.0 to run through AWS Batch?

Thank you for your help!
[config.txt](https://github.com/VirtualFlow/VFVS/files/15280794/config.txt)

**Comment by akshat998** [comment]
@cgorgulla, @mjkoop could you all please take a look at this issue? :)

**Comment by dxu104** [comment]
we tried this solution from the forum https://community.virtual-flow.org/t/how-to-set-proper-docking-input-data-aws-batch/459 but it did not work

**Comment by cgorgulla** [comment]
This same issue is already discussed in the forum: https://community.virtual-flow.org/t/how-to-set-proper-docking-input-data-aws-batch/459/3
